name: build-react-app
defaults:
  run:
    working-directory: my-app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-react:
    strategy:
      matrix: 
        node-version: [18,20,22]
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: install dependencies
        run: npm ci

      - uses: sibiraj-s/action-eslint@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
          working-dir: my-app

      - run: npm run build


