name: build-react-app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: install dependencies
        run: npm ci
        working-directory: my-app

      - run: npm run build
        working-directory: my-app


